add_particles – ALaDyn
add_particles Subroutine
65 statements
Source File
public subroutine add_particles(np, i1, i2, ic)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: np
integer, intent(in) :: i1
integer, intent(in) :: i2
integer, intent(in) :: ic
Calls
Called by
Contents
None
Call graph
add_particles calls init_random_seed, gasdev
particles_inject calls add_particles
comoving_coordinate calls particles_inject
lp_window_xshift calls particles_inject
env_run calls comoving_coordinate, lp_window_xshift
lp_run calls comoving_coordinate, lp_window_xshift
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle