advance_lpf_envelope – ALaDyn
advance_lpf_envelope Subroutine
28 statements
Source File
public subroutine advance_lpf_envelope(curr, evf, omg)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: curr(:,:,:,:)
real(kind=dp), intent(inout) :: evf(:,:,:,:)
real(kind=dp), intent(in) :: omg
Calls
Called by
Contents
None
Call graph
advance_lpf_envelope calls env_maxw_solve, env_bds, fill_ebfield_yzxbdsdata, env_lpf_solve
env_maxw_solve calls potential_lapl
env_bds calls loc_yg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
env_lpf_solve calls pp_lapl
pp_lapl calls loc_yg, loc_zg
env_lpf2_evolve calls advance_lpf_envelope
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle