advance_lpf_fields – ALaDyn
advance_lpf_fields Subroutine
45 statements
Source File
public subroutine advance_lpf_fields(ef, curr, ibd)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: curr(:,:,:,:)
integer, intent(in) :: ibd
Calls
Called by
Contents
None
Call graph
advance_lpf_fields calls ef_bds, bf_bds, fill_ebfield_yzxbdsdata, field_xadvect, rotb, rote
ef_bds calls loc_zgrid, loc_yg, loc_xg, loc_zg
bf_bds calls loc_yg, loc_xg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
rotb calls loc_yg, loc_zg
rote calls loc_yg, loc_zg
lpf2_evolve calls advance_lpf_fields
env_lpf2_evolve calls advance_lpf_fields
env_run calls env_lpf2_evolve
lp_run calls lpf2_evolve
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle