advect_bunch_fields – ALaDyn
advect_bunch_fields Subroutine
20 statements
Source File
public subroutine advect_bunch_fields(fb, curr, v_b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: fb(:,:,:,:)
real(kind=dp), intent(inout) :: curr(:,:,:,:)
real(kind=dp), intent(in) :: v_b
Calls
Contents
None
Call graph
advect_bunch_fields calls fill_ebfield_xbdsdata, field_xadvect
fill_ebfield_xbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1