beam_inject – ALaDyn
beam_inject Subroutine
114 statements
Source File
public subroutine beam_inject()
Arguments
None
Calls
Called by
Contents
None
Call graph
beam_inject calls ebf_bunch, initial_beam_fields, p_alloc, loc_nbpart, init_random_seed, pot, beam_data, fill_ebfield_yzxbdsdata, mpi_beam_ftgrid_distribute, loc_npart, lp_end, ebf, mpi_beam_distribute, ebfp, spec, bunch, jc, ebfb
initial_beam_fields calls loc_yg, loc_zg
beam_data calls ebfb, exchange_2d_grdata, unit_charge
fill_ebfield_yzxbdsdata calls exchange_bdx_data
mpi_beam_ftgrid_distribute calls loc_nbpart, bunch, ebfb
mpi_beam_distribute calls loc_nbpart, bunch, ebfb
env_cycle calls beam_inject
aladyn calls env_cycle