beam_data – ALaDyn
beam_data Subroutine
54 statements
Source File
public subroutine beam_data(ndm)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ndm
Calls
Called by
Contents
None
Call graph
beam_data calls ebfb, unit_charge, exchange_2d_grdata
beam_inject calls beam_data
env_cycle calls beam_inject
aladyn calls env_cycle