bunch_corr – ALaDyn
bunch_corr Subroutine
100 statements
Source File
public subroutine bunch_corr(bch, np_loc, np_norm, bcorr)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: bch(:,:)
integer, intent(in) :: np_loc
real(kind=dp), intent(in) :: np_norm
real(kind=dp), intent(out) :: bcorr(16)
Calls
Called by
Contents
None
Call graph
bunch_corr calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
enb_hgam calls bunch_corr
enb_bunch calls bunch_corr
enb_ionz calls bunch_corr
envar calls enb_bunch
data_out calls envar
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle