comoving_coordinate – ALaDyn
comoving_coordinate Subroutine
33 statements
Source File
public subroutine comoving_coordinate(vb, w_nst, loc_it)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: vb
integer, intent(in) :: w_nst
integer, intent(in) :: loc_it
Calls
Called by
Contents
None
Call graph
comoving_coordinate calls particles_inject, cell_part_dist
particles_inject calls add_particles, loc_npart, v_realloc
cell_part_dist calls loc_npart, v_realloc, ebfp, spec
add_particles calls init_random_seed, gasdev
env_run calls comoving_coordinate
lp_run calls comoving_coordinate
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle