consistency_check_number_of_particles_comp – ALaDyn
consistency_check_number_of_particles_comp Subroutine
7 statements
Source File
private subroutine consistency_check_number_of_particles_comp()
Arguments
None
Calls
Called by
Contents
None
Call graph
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
from_ppc_to_npx_npy_npz calls isprime
read_input_nml calls consistency_check_number_of_particles_comp
read_main_input calls read_input_nml
start calls read_main_input
aladyn calls start