cp_pulse – ALaDyn
cp_pulse Subroutine
27 statements
Source File
public subroutine cp_pulse(cp_mod, part_in)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cp_mod
real(kind=dp), intent(out) :: part_in
Calls
Called by
Contents
None
Call graph
cp_pulse calls init_cp_fields, lp_in, lp_end, loc_xgrid, lpx
init_cp_fields calls loc_zgrid, get_plane_wave_cp, loc_yg, loc_xg, loc_ygrid, loc_zg, get_laser_fields_cp
init calls cp_pulse
start calls init
aladyn calls start