curr_accumulate – ALaDyn
curr_accumulate Subroutine
19 statements
Source File
public subroutine curr_accumulate(sp_loc, pdata, curr, npt)
Arguments
Type Intent Optional Attributes Name
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pdata(:,:)
real(kind=dp), intent(inout) :: curr(:,:,:,:)
integer, intent(in) :: npt
Calls
Contents
None
Call graph
curr_accumulate calls ncdef_3d_curr, ncdef_2d_curr, esirkepov_2d_curr, esirkepov_3d_curr
ncdef_3d_curr calls qlh_3d_spline, set_local_3d_positions
ncdef_2d_curr calls qlh_2d_spline, set_local_2d_positions
esirkepov_2d_curr calls qden_2d_wgh, set_local_2d_positions
esirkepov_3d_curr calls qden_3d_wgh, set_local_3d_positions
set_local_3d_positions calls map3d_part_sind
set_local_2d_positions calls map2dy_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid