dump_data – ALaDyn
dump_data Subroutine
303 statements
Source File
public subroutine dump_data(it_loc, tloc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it_loc
real(kind=dp), intent(in) :: tloc
Calls
Contents
None
Call graph
dump_data calls xpt, loc_zpt, loc_ypt, loc_wghyz, fluid_x_profile, env, wghpt, loc_npart, ebf, up, intvec_distribute, up0, exchange_rdata_int, spec, env1, fluid_yz_profile
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv