ef_bds – ALaDyn
ef_bds Subroutine
104 statements
Source File
public subroutine ef_bds(ef, dtl, imbd)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: dtl
integer, intent(in) :: imbd
Calls
Called by
Contents
None
Call graph
ef_bds calls loc_zgrid, loc_yg, loc_zg, loc_xg
advance_lpf_fields calls ef_bds
lpf2_evolve calls advance_lpf_fields
env_lpf2_evolve calls advance_lpf_fields
env_run calls env_lpf2_evolve
lp_run calls lpf2_evolve
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle