en_data – ALaDyn
en_data Subroutine
6 statements
Source File
public subroutine en_data(nst, itr, idata)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nst
integer, intent(in) :: itr
integer, intent(in) :: idata
Calls
Contents
None
Call graph
en_data calls general_en_data
general_en_data calls mp_per_cell, ion_min, lpy, atomic_number, lpx