enb_bunch – ALaDyn
enb_bunch Subroutine
42 statements
Source File
public subroutine enb_bunch(nst, ib)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nst
integer, intent(in) :: ib
Calls
Called by
Contents
None
Call graph
enb_bunch calls bunch_corr, loc_npart, allreduce_dpreal
bunch_corr calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
envar calls enb_bunch
data_out calls envar
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle