env_run – ALaDyn
env_run Subroutine
23 statements
Source File
public subroutine env_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
env_run calls comoving_coordinate, lp_window_xshift, env_lpf2_evolve
comoving_coordinate calls cell_part_dist, particles_inject
lp_window_xshift calls fluid_left_xshift, fields_left_xshift, cell_part_dist, particles_inject, part_numbers
env_lpf2_evolve calls advance_lpf_envelope, ion_min, loc_npart, ebfp, env_fields_average, env_two_fields_average, update_adam_bash_fluid_variables, enable_ionization, flux, advance_lpf_fields, set_env_momentum_density_flux, env_den_collect, env_amp_two_fields_prepare, init_random_seed, curr_mpi_collect, atomic_number, env_amp_prepare, set_env_density, jc, fluid_curr_accumulate, spec
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
env_fields_average calls env_grad
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, lorentz_fact, nc_fluid_density_momenta, field_xyzbd, unit_charge
advance_lpf_fields calls fill_ebfield_yzxbdsdata, field_xadvect, rotb, rote, ef_bds, bf_bds
env_den_collect calls fill_curr_yzxbdsdata, loc_zg, den_zyxbd, loc_yg
env_amp_two_fields_prepare calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, jc_xyzbd, djc
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
env_amp_prepare calls env_grad
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, field_xyzbd, unit_charge
particles_inject calls loc_npart, v_realloc, add_particles
part_numbers calls loc_npart, intvec_distribute
fill_curr_yzxbdsdata calls exchange_bdx_data
fill_ebfield_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
rotb calls loc_zg, loc_yg
env_maxw_solve calls potential_lapl
intvec_distribute calls mpi_bcast, mpi_recv, mpi_send
rote calls loc_zg, loc_yg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
nc_fluid_density_momenta calls loc_zg, loc_yg
env_bds calls loc_zg, loc_yg
env_lpf_solve calls pp_lapl
add_particles calls init_random_seed, gasdev
bf_bds calls loc_zg, loc_yg, loc_xg
pp_lapl calls loc_zg, loc_yg
env_cycle calls env_run
aladyn calls env_cycle