env_maxw_solve – ALaDyn
env_maxw_solve Subroutine
66 statements
Source File
public subroutine env_maxw_solve(curr, evf, om0, dtl)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: curr(:,:,:,:)
real(kind=dp), intent(inout) :: evf(:,:,:,:)
real(kind=dp), intent(in) :: om0
real(kind=dp), intent(in) :: dtl
Calls
Called by
Contents
None
Call graph
env_maxw_solve calls potential_lapl
advance_lpf_envelope calls env_maxw_solve
env_lpf2_evolve calls advance_lpf_envelope
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle