env_fields_out – ALaDyn
env_fields_out Subroutine
116 statements
Source File
public subroutine env_fields_out(ef, f_ind)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: ef(:,:,:,:)
integer, intent(in) :: f_ind
Calls
Called by
Contents
None
Call graph
env_fields_out calls exchange_pdata
data_out calls env_fields_out
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle