Env_cycle – ALaDyn
Env_cycle Subroutine
23 statements
Source File
subroutine Env_cycle()
Arguments
None
Calls
Called by
Contents
None
Call graph
env_cycle calls timing, part_numbers, error_message, data_out, env_run, beam_inject
timing calls part_numbers, max_pmemory_check, tot_num_part
part_numbers calls loc_npart, intvec_distribute
data_out calls part_pdata_out, env_two_fields_out, fields_out, envar, create_timestep_folder, env_fields_out, fields_out_new, fluid_den_mom_out, den_energy_out, prl_den_energy_interp
env_run calls comoving_coordinate, lp_window_xshift, env_lpf2_evolve
beam_inject calls loc_nbpart, pot, beam_data, fill_ebfield_yzxbdsdata, mpi_beam_ftgrid_distribute, loc_npart, lp_end, ebf, mpi_beam_distribute, ebfp, ebf_bunch, initial_beam_fields, p_alloc, init_random_seed, jc, ebfb, spec, bunch
part_pdata_out calls loc_npart, intvec_distribute, mpi_write_part, endian
env_two_fields_out calls exchange_pdata
fields_out calls exchange_pdata, endian
beam_data calls ebfb, exchange_2d_grdata, unit_charge
fill_ebfield_yzxbdsdata calls exchange_bdx_data
mpi_beam_ftgrid_distribute calls loc_nbpart, ebfb, bunch
comoving_coordinate calls cell_part_dist, particles_inject
lp_window_xshift calls part_numbers, fluid_left_xshift, fields_left_xshift, cell_part_dist, particles_inject
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
mpi_beam_distribute calls loc_nbpart, ebfb, bunch
envar calls loc_npart, enb_bunch, mass, allreduce_dpreal, envelope_struct_data
env_fields_out calls exchange_pdata
max_pmemory_check calls allreduce_dpreal
initial_beam_fields calls loc_zg, loc_yg
env_lpf2_evolve calls loc_npart, ebfp, init_random_seed, jc, spec, advance_lpf_envelope, ion_min, env_fields_average, env_two_fields_average, update_adam_bash_fluid_variables, enable_ionization, flux, advance_lpf_fields, set_env_momentum_density_flux, env_den_collect, env_amp_two_fields_prepare, curr_mpi_collect, atomic_number, env_amp_prepare, set_env_density, fluid_curr_accumulate
fields_out_new calls mpi_write_field, endian
fluid_den_mom_out calls exchange_pdata, endian
tot_num_part calls loc_npart
den_energy_out calls exchange_pdata, endian
prl_den_energy_interp calls loc_npart, jc, spec, env, den_zyxbd, loc_zg, loc_yg, mass
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
env_fields_average calls env_grad
mpi_write_part calls mpi_file_set_view, mpi_file_write, mpi_file_close, mpi_file_open
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, nc_fluid_density_momenta, field_xyzbd
advance_lpf_fields calls fill_ebfield_yzxbdsdata, field_xadvect, rotb, rote, ef_bds, bf_bds
env_den_collect calls loc_zg, loc_yg, fill_curr_yzxbdsdata, den_zyxbd
env_amp_two_fields_prepare calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, jc_xyzbd, djc
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
env_amp_prepare calls env_grad
mpi_write_field calls mpi_file_set_view, mpi_file_write, mpi_file_close, mpi_file_open
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
particles_inject calls loc_npart, v_realloc, add_particles
allreduce_dpreal calls mpi_allreduce
envelope_struct_data calls allreduce_dpreal
bunch_corr calls allreduce_dpreal
fill_curr_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
rotb calls loc_zg, loc_yg
env_maxw_solve calls potential_lapl
rote calls loc_zg, loc_yg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
nc_fluid_density_momenta calls loc_zg, loc_yg
env_bds calls loc_zg, loc_yg
env_lpf_solve calls pp_lapl
add_particles calls init_random_seed, gasdev
bf_bds calls loc_zg, loc_yg, loc_xg
pp_lapl calls loc_zg, loc_yg
aladyn calls env_cycle