env_lpf2_evolve – ALaDyn
env_lpf2_evolve Subroutine
99 statements
Source File
public subroutine env_lpf2_evolve(it_loc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it_loc
Calls
Called by
Contents
None
Call graph
env_lpf2_evolve calls advance_lpf_envelope, ion_min, loc_npart, ebfp, env_fields_average, env_two_fields_average, update_adam_bash_fluid_variables, enable_ionization, flux, advance_lpf_fields, set_env_momentum_density_flux, env_den_collect, env_amp_two_fields_prepare, init_random_seed, curr_mpi_collect, atomic_number, env_amp_prepare, set_env_density, jc, fluid_curr_accumulate, spec
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
env_fields_average calls env_grad
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, lorentz_fact, nc_fluid_density_momenta, field_xyzbd, unit_charge
advance_lpf_fields calls fill_ebfield_yzxbdsdata, field_xadvect, rotb, rote, ef_bds, bf_bds
env_den_collect calls fill_curr_yzxbdsdata, loc_zg, den_zyxbd, loc_yg
env_amp_two_fields_prepare calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, jc_xyzbd, djc
env_amp_prepare calls env_grad
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, field_xyzbd, unit_charge
fill_curr_yzxbdsdata calls exchange_bdx_data
fill_ebfield_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
rotb calls loc_zg, loc_yg
env_maxw_solve calls potential_lapl
rote calls loc_zg, loc_yg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
nc_fluid_density_momenta calls loc_zg, loc_yg
env_bds calls loc_zg, loc_yg
env_lpf_solve calls pp_lapl
bf_bds calls loc_zg, loc_yg, loc_xg
pp_lapl calls loc_zg, loc_yg
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle