Envar – ALaDyn
Envar Subroutine
201 statements
Source File
public subroutine Envar(nst)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nst
Calls
Called by
Contents
None
Call graph
envar calls allreduce_dpreal, loc_npart, envelope_struct_data, enb_bunch, mass
allreduce_dpreal calls mpi_allreduce
envelope_struct_data calls allreduce_dpreal
enb_bunch calls allreduce_dpreal, loc_npart, bunch_corr
bunch_corr calls allreduce_dpreal
data_out calls envar
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle