envelope_struct_data – ALaDyn
envelope_struct_data Subroutine
143 statements
Source File
public subroutine envelope_struct_data(nst)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nst
Calls
Called by
Contents
None
Call graph
envelope_struct_data calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
envar calls envelope_struct_data
data_out calls envar
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle