esirkepov_3d_curr – ALaDyn
esirkepov_3d_curr Subroutine
140 statements
Source File
public subroutine esirkepov_3d_curr(sp_loc, pt, jcurr, np)
Arguments
Type Intent Optional Attributes Name
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pt(:,:)
real(kind=dp), intent(inout) :: jcurr(:,:,:,:)
integer, intent(in) :: np
Calls
Called by
Contents
None
Call graph
esirkepov_3d_curr calls qden_3d_wgh, set_local_3d_positions
set_local_3d_positions calls map3d_part_sind
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid
curr_accumulate calls esirkepov_3d_curr