esirkepov_2d_curr – ALaDyn
esirkepov_2d_curr Subroutine
183 statements
Source File
public subroutine esirkepov_2d_curr(sp_loc, pt, jcurr, np)
Arguments
Type Intent Optional Attributes Name
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pt(:,:)
real(kind=dp), intent(inout) :: jcurr(:,:,:,:)
integer, intent(in) :: np
Calls
Called by
Contents
None
Call graph
esirkepov_2d_curr calls set_local_2d_positions, qden_2d_wgh
set_local_2d_positions calls map2dy_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
curr_accumulate calls esirkepov_2d_curr