exchange_pdata – ALaDyn
exchange_pdata Subroutine
10 statements
Source File
public subroutine exchange_pdata(sr, pdata, lenw, ipe, tag)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: sr
real(kind=sp), intent(inout) :: pdata(:)
integer, intent(in) :: lenw
integer, intent(in) :: ipe
integer, intent(in) :: tag
Called by
Contents
None
Call graph
bfields_out calls exchange_pdata
env_two_fields_out calls exchange_pdata
fields_out calls exchange_pdata
bden_energy_out calls exchange_pdata
env_fields_out calls exchange_pdata
ext_bfield_out calls exchange_pdata
fluid_den_mom_out calls exchange_pdata
den_energy_out calls exchange_pdata
data_out calls env_two_fields_out, fields_out, env_fields_out, fluid_den_mom_out, den_energy_out
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle