exchange_bdx_data – ALaDyn
exchange_bdx_data Subroutine
35 statements
Source File
public subroutine exchange_bdx_data(buff1, buff2, lenws, lenwr, dir, side)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: buff1(:)
real(kind=dp), intent(out) :: buff2(:)
integer, intent(in) :: lenws
integer, intent(in) :: lenwr
integer, intent(in) :: dir
integer(kind=hp_int), intent(in) :: side
Called by
Contents
None
Call graph
fluid_left_xshift calls exchange_bdx_data
fill_curr_yzxbdsdata calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
fill_ebfield_yzxbdsdata calls exchange_bdx_data
fill_ebfield_xbdsdata calls exchange_bdx_data
fill_ftcurr_yzbdsdata calls exchange_bdx_data
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata
pfields_prepare calls fill_ebfield_yzxbdsdata
advance_lpf_envelope calls fill_ebfield_yzxbdsdata
curr_mpi_collect calls fill_curr_yzxbdsdata
collect_bunch_and_plasma_density calls fill_curr_yzxbdsdata
set_wake_potential calls fill_curr_yzxbdsdata
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata
prl_bden_energy_interp calls fill_curr_yzxbdsdata
lp_window_xshift calls fluid_left_xshift, fields_left_xshift
advect_bunch_fields calls fill_ebfield_xbdsdata
advance_lpf_fields calls fill_ebfield_yzxbdsdata
beam_inject calls fill_ebfield_yzxbdsdata
lpf2_evolve calls fluid_curr_accumulate, pfields_prepare, update_adam_bash_fluid_variables, advance_lpf_fields
env_cycle calls beam_inject, env_run
lp_run calls lp_window_xshift, lpf2_evolve
env_lpf2_evolve calls fluid_curr_accumulate, advance_lpf_envelope, curr_mpi_collect, update_adam_bash_fluid_variables, advance_lpf_fields
env_run calls lp_window_xshift, env_lpf2_evolve
lp_cycle calls lp_run
aladyn calls env_cycle, lp_cycle