fft_3d_psolv – ALaDyn
fft_3d_psolv Subroutine
53 statements
Source File
public subroutine fft_3d_psolv(rho, pot1, g2, omp0, n1, n1_loc, n2, n2_loc, n3, n3_loc, i1, i2, j1, j2, k1, k2, ft_mod, sym, s_ind)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: rho(:,:,:,:)
real(kind=dp), intent(inout) :: pot1(:,:,:,:)
real(kind=dp), intent(in) :: g2
real(kind=dp), intent(in) :: omp0
integer, intent(in) :: n1
integer, intent(in) :: n1_loc
integer, intent(in) :: n2
integer, intent(in) :: n2_loc
integer, intent(in) :: n3
integer, intent(in) :: n3_loc
integer, intent(in) :: i1
integer, intent(in) :: i2
integer, intent(in) :: j1
integer, intent(in) :: j2
integer, intent(in) :: k1
integer, intent(in) :: k2
integer, intent(in) :: ft_mod
integer, intent(in) :: sym
integer, intent(in) :: s_ind
Calls
Contents
None
Call graph
fft_3d_psolv calls pftw3d, beam_potential, mpi_ftw_alloc, all_gather_dpreal, mpi_yzft_ord, pftw3d_sc, ftw_init, unif_to_str_field_interp, mpi_ftw_dalloc, ftw_end, ft_overset_grid
pftw3d calls ftw1d, pftw2d
pftw3d_sc calls ftw1d_sc, pftw2d_sc
unif_to_str_field_interp calls yft_ind, loc_yg, loc_zft, zft_ind, loc_zg, loc_yft
ft_overset_grid calls zp_next, zp_prev, yp_next, comm_col, yp_prev
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
pftw2d calls ftw1d, swap_xy_3data, swap_xy_3data_inv, swap_xz_3data, swap_xz_3data_inv
ftw1d_sc calls fftw_execute_r2r, determine_kind, logical_dimension
pftw2d_sc calls ftw1d_sc, swap_xy_3data, swap_xy_3data_inv, swap_xz_3data, swap_xz_3data_inv
swap_xy_3data calls yp_next, comm_col, yp_prev
swap_xy_3data_inv calls yp_next, comm_col, yp_prev
swap_xz_3data calls zp_next, zp_prev, comm_col
swap_xz_3data_inv calls zp_next, zp_prev, comm_col