field_xyzbd – ALaDyn
field_xyzbd Subroutine
133 statements
Source File
public subroutine field_xyzbd(ef, nc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
integer, intent(in) :: nc
Called by
Contents
None
Call graph
pfields_prepare calls field_xyzbd
update_adam_bash_fluid_variables calls field_xyzbd
fluid_curr_accumulate calls field_xyzbd
lpf2_evolve calls pfields_prepare, update_adam_bash_fluid_variables, fluid_curr_accumulate
env_lpf2_evolve calls update_adam_bash_fluid_variables, fluid_curr_accumulate
env_run calls env_lpf2_evolve
lp_run calls lpf2_evolve
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle