fields_out_new – ALaDyn
fields_out_new Subroutine
135 statements
Source File
public subroutine fields_out_new(ef, f_ind, var_ind)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: ef(:,:,:,:)
integer, intent(in) :: f_ind
integer, intent(in) :: var_ind
Calls
Called by
Contents
None
Call graph
fields_out_new calls mpi_write_field, endian
mpi_write_field calls mpi_file_set_view, mpi_file_open, mpi_file_close, mpi_file_write
data_out calls fields_out_new
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle