field_xadvect – ALaDyn
field_xadvect Subroutine
91 statements
Source File
public subroutine field_xadvect(ef, dth, v_adv, ic1, ic2, isch)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: dth
real(kind=dp), intent(in) :: v_adv
integer, intent(in) :: ic1
integer, intent(in) :: ic2
integer, intent(in) :: isch
Calls
Called by
Contents
None
Call graph
field_xadvect calls trid_der1
advance_lpf_fields calls field_xadvect
advect_bunch_fields calls field_xadvect
lpf2_evolve calls advance_lpf_fields
env_lpf2_evolve calls advance_lpf_fields
env_run calls env_lpf2_evolve
lp_run calls lpf2_evolve
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle