fill_ebfield_yzxbdsdata – ALaDyn
fill_ebfield_yzxbdsdata Subroutine
255 statements
Source File
public subroutine fill_ebfield_yzxbdsdata(fld, ic1, ic2, str, stl)
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: fld(:,:,:,:)
integer, intent(in) :: ic1
integer, intent(in) :: ic2
integer, intent(in) :: str
integer, intent(in) :: stl
Calls
Called by
Contents
None
Call graph
fill_ebfield_yzxbdsdata calls exchange_bdx_data
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata
pfields_prepare calls fill_ebfield_yzxbdsdata
advance_lpf_envelope calls fill_ebfield_yzxbdsdata
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata
advance_lpf_fields calls fill_ebfield_yzxbdsdata
beam_inject calls fill_ebfield_yzxbdsdata
env_cycle calls beam_inject, env_run
lpf2_evolve calls fluid_curr_accumulate, pfields_prepare, update_adam_bash_fluid_variables, advance_lpf_fields
env_lpf2_evolve calls fluid_curr_accumulate, advance_lpf_envelope, update_adam_bash_fluid_variables, advance_lpf_fields
env_run calls env_lpf2_evolve
lp_run calls lpf2_evolve
aladyn calls env_cycle, lp_cycle
lp_cycle calls lp_run