fill_curr_yzxbdsdata – ALaDyn
fill_curr_yzxbdsdata Subroutine
259 statements
Source File
public subroutine fill_curr_yzxbdsdata(curr, nc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: curr(:,:,:,:)
integer, intent(in) :: nc
Calls
Called by
Contents
None
Call graph
fill_curr_yzxbdsdata calls exchange_bdx_data
set_wake_potential calls fill_curr_yzxbdsdata
prl_bden_energy_interp calls fill_curr_yzxbdsdata
curr_mpi_collect calls fill_curr_yzxbdsdata
collect_bunch_and_plasma_density calls fill_curr_yzxbdsdata
env_lpf2_evolve calls curr_mpi_collect
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle