fill_density_data – ALaDyn
fill_density_data Subroutine
28 statements
Source File
public subroutine fill_density_data(den, ic)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: den(:,:,:,:)
integer, intent(in) :: ic
Calls
Called by
Contents
None
Call graph
fill_density_data calls loc_zgrid, y, x, loc_ygrid, z
set_wake_potential calls fill_density_data