fluid_curr_accumulate – ALaDyn
fluid_curr_accumulate Subroutine
72 statements
Source File
public subroutine fluid_curr_accumulate(flx, curr)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: flx(:,:,:,:)
real(kind=dp), intent(inout) :: curr(:,:,:,:)
Calls
Called by
Contents
None
Call graph
fluid_curr_accumulate calls field_xyzbd, fill_ebfield_yzxbdsdata, unit_charge
fill_ebfield_yzxbdsdata calls exchange_bdx_data
lpf2_evolve calls fluid_curr_accumulate
env_lpf2_evolve calls fluid_curr_accumulate
env_run calls env_lpf2_evolve
lp_run calls lpf2_evolve
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle