fluid_left_xshift – ALaDyn
fluid_left_xshift Subroutine
86 statements
Source File
public subroutine fluid_left_xshift(fld, den_x, den_yz, i1, i2, ic1, ic2, xsh)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: fld(:,:,:,:)
real(kind=dp), intent(in) :: den_x(:)
real(kind=dp), intent(in) :: den_yz(:,:)
integer, intent(in) :: i1
integer, intent(in) :: i2
integer, intent(in) :: ic1
integer, intent(in) :: ic2
integer, intent(in) :: xsh
Calls
Called by
Contents
None
Call graph
fluid_left_xshift calls exchange_bdx_data
lp_window_xshift calls fluid_left_xshift
env_run calls lp_window_xshift
lp_run calls lp_window_xshift
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle