ft_overset_grid – ALaDyn
ft_overset_grid Subroutine
102 statements
Source File
public subroutine ft_overset_grid(w_s, w_r, nft1, nft2, nft3)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: w_s(:,:,:)
real(kind=dp), intent(out) :: w_r(:,:,:)
integer, intent(in) :: nft1
integer, intent(in) :: nft2
integer, intent(in) :: nft3
Calls
Called by
Contents
None
Call graph
ft_overset_grid calls zp_next, zp_prev, yp_next, comm_col, yp_prev
fft_2d_psolv calls ft_overset_grid
fft_3d_psolv calls ft_overset_grid
set_wake_potential calls fft_2d_psolv