ftw1d – ALaDyn
ftw1d Subroutine
189 statements
Source File
public subroutine ftw1d(w, n1, n2, n3, is, dir)
WARNING: Still to be checked
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: w(:,:,:)
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n3
integer, intent(in) :: is
integer, intent(in) :: dir
Calls
Called by
Contents
None
Call graph
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
pftw2d calls ftw1d
pftw3d calls ftw1d, pftw2d
fft_2d_psolv calls pftw2d
fft_3d_psolv calls pftw3d
set_wake_potential calls fft_2d_psolv