inflow_lp_fields – ALaDyn
inflow_lp_fields Subroutine
268 statements
Source File
public subroutine inflow_lp_fields(ef, ee0, t_loc, tf, wx, wy, xf0, om0, lp, i, j1, j2, k1, k2)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: ee0
real(kind=dp), intent(in) :: t_loc
real(kind=dp), intent(in) :: tf
real(kind=dp), intent(in) :: wx
real(kind=dp), intent(in) :: wy
real(kind=dp), intent(in) :: xf0
real(kind=dp), intent(in) :: om0
integer, intent(in) :: lp
integer, intent(in) :: i
integer, intent(in) :: j1
integer, intent(in) :: j2
integer, intent(in) :: k1
integer, intent(in) :: k2
Calls
Called by
Contents
None
Call graph
inflow_lp_fields calls get_plane_wave_lp, get_laser_fields_lp, get_2dlaser_fields_lp, loc_yg, loc_xg, get_2dlaser_gprof_fields_lp, loc_zg
wave_field_left_inject calls inflow_lp_fields