init – ALaDyn
init Subroutine
14 statements
Source File
public subroutine init()
Arguments
None
Calls
Called by
Contents
None
Call graph
init calls lp_pulse, part_distribute, cp_pulse, set_envelope
lp_pulse calls y0_cent, lp_end, loc_xgrid, init_lp_inc0_fields, z0_cent, xc_loc, lp_in, xf_loc, lp_delay, lpx
part_distribute calls multi_layer_threesp_target, multi_layer_gas_target, preplasma_multisp, one_layer_nano_tubes, one_layer_nano_wires, multi_layer_twosp_target
cp_pulse calls init_cp_fields, lp_end, loc_xgrid, lp_in, lpx
set_envelope calls y0_cent, lp_end, loc_xgrid, init_gprof_envelope_field, z0_cent, init_envelope_field, xc_loc, lp_in, xf_loc, lp_delay, lpx
init_cp_fields calls get_plane_wave_cp, loc_zg, get_laser_fields_cp, loc_zgrid, loc_yg, loc_xg, loc_ygrid
init_gprof_envelope_field calls loc_zg, loc_zgrid, loc_yg, loc_xg, loc_ygrid
multi_layer_threesp_target calls wghpt, loc_xpt, loc_wghx, p_alloc, set_uniform_yz_distrib, xpt, spec
init_lp_inc0_fields calls get_2dlaser_gprof_fields_lp, get_laser_gprof_fields_lp, loc_zg, loc_zgrid, get_laser_fields_lp, get_2dlaser_fields_lp, loc_yg, loc_xg, get_plane_wave_lp, loc_ygrid
multi_layer_gas_target calls wghpt, loc_xpt, loc_wghx, p_alloc, set_uniform_yz_distrib, mpi_x_part_distrib, xpt, spec
preplasma_multisp calls wghpt, loc_xpt, loc_wghx, p_alloc, set_uniform_yz_distrib, xpt, spec
init_envelope_field calls loc_zg, loc_zgrid, loc_yg, loc_xg, loc_ygrid
one_layer_nano_tubes calls wghpt, loc_xpt, zpt, mpi_yz_part_distrib, p_alloc, loc_wghyz, init_random_seed, xpt, loc_ypt, loc_zpt, ypt, spec, gasdev
one_layer_nano_wires calls wghpt, loc_xpt, loc_wghx, set_pgrid_ind, zpt, mpi_yz_part_distrib, p_alloc, loc_wghyz, xpt, loc_ypt, loc_zpt, ypt, spec
multi_layer_twosp_target calls wghpt, loc_xpt, loc_wghx, p_alloc, set_uniform_yz_distrib, xpt, spec
set_pgrid_ind calls zpt, ypt
mpi_yz_part_distrib calls zpt, loc_wghyz, loc_ypt, loc_zpt, ypt
set_uniform_yz_distrib calls set_pgrid_ind, zpt, mpi_yz_part_distrib, loc_wghyz, loc_ypt, loc_zpt, ypt
mpi_x_part_distrib calls wghpt, loc_xpt, loc_wghx, xpt
start calls init
aladyn calls start