init_cp_fields – ALaDyn
init_cp_fields Subroutine
148 statements
Source File
public subroutine init_cp_fields(ef, ee0, t_loc, tf, wx, wy, xf0, angle, lp_shx, cp, i1, i2)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: ee0
real(kind=dp), intent(in) :: t_loc
real(kind=dp), intent(in) :: tf
real(kind=dp), intent(in) :: wx
real(kind=dp), intent(in) :: wy
real(kind=dp), intent(in) :: xf0
real(kind=dp), intent(in) :: angle
real(kind=dp), intent(in) :: lp_shx
integer, intent(in) :: cp
integer, intent(in) :: i1
integer, intent(in) :: i2
Calls
Called by
Contents
None
Call graph
init_cp_fields calls loc_zgrid, get_plane_wave_cp, loc_yg, loc_xg, loc_ygrid, loc_zg, get_laser_fields_cp
cp_pulse calls init_cp_fields
init calls cp_pulse
start calls init
aladyn calls start