init_lp_inc0_fields – ALaDyn
init_lp_inc0_fields Subroutine
345 statements
Source File
public subroutine init_lp_inc0_fields(ef, ee0, t_loc, tf, wx, wy, xf0, om0, lp, i1, i2, ycent, zcent)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: ee0
real(kind=dp), intent(in) :: t_loc
real(kind=dp), intent(in) :: tf
real(kind=dp), intent(in) :: wx
real(kind=dp), intent(in) :: wy
real(kind=dp), intent(in) :: xf0
real(kind=dp), intent(in) :: om0
integer, intent(in) :: lp
integer, intent(in) :: i1
integer, intent(in) :: i2
real(kind=dp) :: ycent
real(kind=dp) :: zcent
Calls
Called by
Contents
None
Call graph
init_lp_inc0_fields calls loc_zgrid, get_plane_wave_lp, get_laser_fields_lp, get_2dlaser_fields_lp, loc_yg, loc_xg, get_2dlaser_gprof_fields_lp, loc_ygrid, get_laser_gprof_fields_lp, loc_zg
lp_pulse calls init_lp_inc0_fields
init calls lp_pulse
start calls init
aladyn calls start