initial_tparticles_select – ALaDyn
initial_tparticles_select Subroutine
76 statements
Source File
public subroutine initial_tparticles_select(tx1, ty1)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: tx1
real(kind=dp), intent(in) :: ty1
Calls
Contents
None
Call graph
initial_tparticles_select calls loc_tpart, t0_pl, intvec_distribute, loc_npart, loc_ygrid, pdata_tracking, ebfp, spec, track_aux