init_gprof_envelope_field – ALaDyn
init_gprof_envelope_field Subroutine
113 statements
Source File
public subroutine init_gprof_envelope_field(ef, ee0, t_loc, tf, wx, wy, xf0, om0, pw, i1, i2, ycent, zcent)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: ee0
real(kind=dp), intent(in) :: t_loc
real(kind=dp), intent(in) :: tf
real(kind=dp), intent(in) :: wx
real(kind=dp), intent(in) :: wy
real(kind=dp), intent(in) :: xf0
real(kind=dp), intent(in) :: om0
integer, intent(in) :: pw
integer, intent(in) :: i1
integer, intent(in) :: i2
real(kind=dp) :: ycent
real(kind=dp) :: zcent
Calls
Called by
Contents
None
Call graph
init_gprof_envelope_field calls loc_zgrid, loc_yg, loc_xg, loc_ygrid, loc_zg
set_envelope calls init_gprof_envelope_field
init calls set_envelope
start calls init
aladyn calls start