ionization_electrons_inject – ALaDyn
ionization_electrons_inject Subroutine
58 statements
Source File
private subroutine ionization_electrons_inject(ion_ch_inc, ic, np, np_el, new_np_el)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ion_ch_inc(:)
integer, intent(in) :: ic
integer, intent(in) :: np
integer, intent(inout) :: np_el
integer, intent(in) :: new_np_el
Calls
Called by
Contents
None
Call graph
ionization_electrons_inject calls spec, gasdev
ionization_cycle calls ionization_electrons_inject