ionization_cycle – ALaDyn
ionization_cycle Subroutine
67 statements
Source File
public subroutine ionization_cycle(sp_loc, sp_aux, np, ic, itloc, mom_id, def_inv)
Arguments
Type Intent Optional Attributes Name
type(species), intent(inout) :: sp_loc
real(kind=dp), intent(inout) :: sp_aux(:,:)
integer, intent(in) :: np
integer, intent(in) :: ic
integer, intent(in) :: itloc
integer, intent(in) :: mom_id
real(kind=dp), intent(in) :: def_inv
Calls
Contents
None
Call graph
ionization_cycle calls env_ionization_electrons_inject, v_realloc, part_ionize, ebfp, ionization_electrons_inject, spec
env_ionization_electrons_inject calls spec, gasdev
ionization_electrons_inject calls spec, gasdev