laser_struct_data – ALaDyn
laser_struct_data Subroutine
56 statements
Source File
public subroutine laser_struct_data(nst)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nst
Calls
Contents
None
Call graph
laser_struct_data calls lp_in, lp_end, allreduce_dpreal
allreduce_dpreal calls mpi_allreduce