Lp_cycle – ALaDyn
Lp_cycle Subroutine
15 statements
Source File
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
Calls
Called by
Contents
None
Call graph
lp_cycle calls data_out, lp_run, error_message, timing
data_out calls part_pdata_out, create_timestep_folder, env_two_fields_out, fields_out, prl_den_energy_interp, env_fields_out, fields_out_new, fluid_den_mom_out, den_energy_out, envar
lp_run calls lpf2_evolve, comoving_coordinate, lp_window_xshift
timing calls part_numbers, max_pmemory_check, tot_num_part
part_pdata_out calls loc_npart, endian, intvec_distribute, mpi_write_part
lpf2_evolve calls pfields_prepare, ion_min, loc_npart, ebfp, update_adam_bash_fluid_variables, advance_lpf_fields, set_momentum_density_flux, init_random_seed, atomic_number, jc, fluid_curr_accumulate, spec
part_numbers calls loc_npart, intvec_distribute
env_two_fields_out calls exchange_pdata
fields_out calls endian, exchange_pdata
prl_den_energy_interp calls loc_npart, env, den_zyxbd, loc_zg, loc_yg, mass, jc, spec
comoving_coordinate calls cell_part_dist, particles_inject
env_fields_out calls exchange_pdata
max_pmemory_check calls allreduce_dpreal
lp_window_xshift calls part_numbers, fluid_left_xshift, fields_left_xshift, cell_part_dist, particles_inject
tot_num_part calls loc_npart
fields_out_new calls endian, mpi_write_field
fluid_den_mom_out calls endian, exchange_pdata
den_energy_out calls endian, exchange_pdata
envar calls loc_npart, enb_bunch, mass, allreduce_dpreal, envelope_struct_data
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
mpi_write_part calls mpi_file_set_view, mpi_file_write, mpi_file_close, mpi_file_open
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, lorentz_fact, nc_fluid_density_momenta, field_xyzbd, unit_charge
advance_lpf_fields calls fill_ebfield_yzxbdsdata, field_xadvect, rotb, rote, ef_bds, bf_bds
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
mpi_write_field calls mpi_file_set_view, mpi_file_write, mpi_file_close, mpi_file_open
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, field_xyzbd, unit_charge
particles_inject calls loc_npart, v_realloc, add_particles
allreduce_dpreal calls mpi_allreduce
envelope_struct_data calls allreduce_dpreal
bunch_corr calls allreduce_dpreal
fill_ebfield_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
rotb calls loc_zg, loc_yg
rote calls loc_zg, loc_yg
ef_bds calls loc_zg, loc_yg, loc_zgrid, loc_xg
nc_fluid_density_momenta calls loc_zg, loc_yg
add_particles calls init_random_seed, gasdev
bf_bds calls loc_zg, loc_yg, loc_xg
aladyn calls lp_cycle