lp_run – ALaDyn
lp_run Subroutine
21 statements
Source File
public subroutine lp_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lp_run calls comoving_coordinate, lpf2_evolve, lp_window_xshift
comoving_coordinate calls particles_inject, cell_part_dist
lpf2_evolve calls set_momentum_density_flux, fluid_curr_accumulate, spec, pfields_prepare, init_random_seed, ion_min, update_adam_bash_fluid_variables, loc_npart, atomic_number, ebfp, advance_lpf_fields, jc
lp_window_xshift calls particles_inject, fluid_left_xshift, fields_left_xshift, part_numbers, cell_part_dist
particles_inject calls loc_npart, add_particles, v_realloc
fluid_curr_accumulate calls field_xyzbd, fill_ebfield_yzxbdsdata, unit_charge
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
pfields_prepare calls field_xyzbd, fill_ebfield_yzxbdsdata
part_numbers calls loc_npart, intvec_distribute
cell_part_dist calls spec, loc_npart, ebfp, v_realloc
update_adam_bash_fluid_variables calls field_xyzbd, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta, unit_charge, lorentz_fact
advance_lpf_fields calls rote, ef_bds, bf_bds, fill_ebfield_yzxbdsdata, field_xadvect, rotb
add_particles calls init_random_seed, gasdev
rote calls loc_yg, loc_zg
ef_bds calls loc_zgrid, loc_yg, loc_xg, loc_zg
bf_bds calls loc_yg, loc_xg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
nc_fluid_density_momenta calls loc_yg, loc_zg
intvec_distribute calls mpi_bcast, mpi_recv, mpi_send
rotb calls loc_yg, loc_zg
lp_cycle calls lp_run
aladyn calls lp_cycle