lp_window_xshift – ALaDyn
lp_window_xshift Subroutine
62 statements
Source File
public subroutine lp_window_xshift(witr, init_iter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: witr
integer, intent(in) :: init_iter
Calls
Called by
Contents
None
Call graph
lp_window_xshift calls fluid_left_xshift, fields_left_xshift, particles_inject, part_numbers, cell_part_dist
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
particles_inject calls add_particles, loc_npart, v_realloc
part_numbers calls loc_npart, intvec_distribute
cell_part_dist calls loc_npart, v_realloc, ebfp, spec
add_particles calls init_random_seed, gasdev
intvec_distribute calls mpi_bcast, mpi_recv, mpi_send
env_run calls lp_window_xshift
lp_run calls lp_window_xshift
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle