lpf2_evolve – ALaDyn
lpf2_evolve Subroutine
47 statements
Source File
public subroutine lpf2_evolve(iter_loc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lpf2_evolve calls set_momentum_density_flux, fluid_curr_accumulate, spec, pfields_prepare, init_random_seed, ion_min, update_adam_bash_fluid_variables, loc_npart, atomic_number, ebfp, advance_lpf_fields, jc
fluid_curr_accumulate calls field_xyzbd, fill_ebfield_yzxbdsdata, unit_charge
pfields_prepare calls field_xyzbd, fill_ebfield_yzxbdsdata
update_adam_bash_fluid_variables calls field_xyzbd, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta, unit_charge, lorentz_fact
advance_lpf_fields calls rote, ef_bds, bf_bds, fill_ebfield_yzxbdsdata, field_xadvect, rotb
rote calls loc_yg, loc_zg
ef_bds calls loc_zgrid, loc_yg, loc_xg, loc_zg
bf_bds calls loc_yg, loc_xg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
nc_fluid_density_momenta calls loc_yg, loc_zg
rotb calls loc_yg, loc_zg
lp_run calls lpf2_evolve
lp_cycle calls lp_run
aladyn calls lp_cycle