map3d_part_sind – ALaDyn
map3d_part_sind Subroutine
6 statements
Source File
public subroutine map3d_part_sind(pt, np, ic1, ic2)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: pt(:,:)
integer, intent(in) :: np
integer, intent(in) :: ic1
integer, intent(in) :: ic2
Calls
Called by
Contents
None
Call graph
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid
set_local_3d_positions calls map3d_part_sind
set_grid_charge_and_jx calls set_local_3d_positions
set_grid_env_den_energy calls set_local_3d_positions
esirkepov_3d_curr calls set_local_3d_positions
set_env_grad_interp calls set_local_3d_positions
ncdef_3d_curr calls set_local_3d_positions
set_env_density calls set_local_3d_positions
set_ion_efield calls set_local_3d_positions
set_env_acc calls set_local_3d_positions
set_grid_charge calls set_local_3d_positions
set_part3d_hcell_acc calls set_local_3d_positions
set_grid_den_energy calls set_local_3d_positions
set_ion_env_field calls set_local_3d_positions
set_lpf_acc calls set_part3d_hcell_acc
curr_accumulate calls esirkepov_3d_curr, ncdef_3d_curr