Max_pmemory_check – ALaDyn
Max_pmemory_check Subroutine
45 statements
Source File
public subroutine Max_pmemory_check()
Arguments
None
Calls
Called by
Contents
None
Call graph
max_pmemory_check calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
aladyn calls max_pmemory_check, lp_cycle, env_cycle
timing calls max_pmemory_check
lp_cycle calls timing
env_cycle calls timing