mpi_yzft_ord – ALaDyn
mpi_yzft_ord Subroutine
30 statements
Source File
public subroutine mpi_yzft_ord(ny_ft, nz_ft)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ny_ft
integer, intent(in) :: nz_ft
Called by
Contents
None
Call graph
fft_2d_psolv calls mpi_yzft_ord
fft_3d_psolv calls mpi_yzft_ord
set_wake_potential calls fft_2d_psolv