mpi_write_part – ALaDyn
mpi_write_part Subroutine
12 statements
Source File
public subroutine mpi_write_part(buf, bufsize, loc_np, disp, nchar, fout)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: buf(:)
integer, intent(in) :: bufsize
integer, intent(in) :: loc_np
integer(kind=offset_kind), intent(in) :: disp
integer, intent(in) :: nchar
character(len=nchar), intent(in) :: fout
Calls
Called by
Contents
None
Call graph
mpi_write_part calls mpi_file_set_view, mpi_file_open, mpi_file_close, mpi_file_write
part_pdata_out calls mpi_write_part
part_high_gamma_out calls mpi_write_part
part_ionz_out calls mpi_write_part
part_bdata_out calls mpi_write_part
data_out calls part_pdata_out
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle