multi_layer_gas_target – ALaDyn
multi_layer_gas_target Subroutine
424 statements
Source File
private subroutine multi_layer_gas_target(layer_mod, nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: layer_mod
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
multi_layer_gas_target calls xpt, p_alloc, loc_wghx, set_uniform_yz_distrib, wghpt, mpi_x_part_distrib, spec, loc_xpt
set_uniform_yz_distrib calls mpi_yz_part_distrib, loc_zpt, loc_ypt, loc_wghyz, set_pgrid_ind, ypt, zpt
mpi_x_part_distrib calls xpt, loc_wghx, wghpt, loc_xpt
mpi_yz_part_distrib calls loc_zpt, loc_ypt, loc_wghyz, ypt, zpt
set_pgrid_ind calls ypt, zpt
part_distribute calls multi_layer_gas_target
init calls part_distribute
start calls init
aladyn calls start