one_layer_nano_wires – ALaDyn
one_layer_nano_wires Subroutine
375 statements
Source File
private subroutine one_layer_nano_wires(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
one_layer_nano_wires calls xpt, mpi_yz_part_distrib, loc_zpt, loc_ypt, loc_wghyz, p_alloc, ypt, loc_wghx, wghpt, set_pgrid_ind, spec, loc_xpt, zpt
mpi_yz_part_distrib calls loc_zpt, loc_ypt, loc_wghyz, ypt, zpt
set_pgrid_ind calls ypt, zpt
part_distribute calls one_layer_nano_wires
init calls part_distribute
start calls init
aladyn calls start