one_layer_nano_tubes – ALaDyn
one_layer_nano_tubes Subroutine
257 statements
Source File
private subroutine one_layer_nano_tubes(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
one_layer_nano_tubes calls xpt, mpi_yz_part_distrib, loc_zpt, loc_ypt, loc_wghyz, p_alloc, init_random_seed, ypt, wghpt, spec, gasdev, loc_xpt, zpt
mpi_yz_part_distrib calls loc_zpt, loc_ypt, loc_wghyz, ypt, zpt
part_distribute calls one_layer_nano_tubes
init calls part_distribute
start calls init
aladyn calls start