p_alloc – ALaDyn
p_alloc Subroutine
36 statements
Source File
public subroutine p_alloc(npt_max, ncmp, np_s, ns, lp, mid, r_type, msize)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npt_max
integer, intent(in) :: ncmp
integer, intent(in) :: np_s(:)
integer, intent(in) :: ns
integer, intent(in) :: lp
integer, intent(in) :: mid
integer, intent(in) :: r_type
integer, intent(inout) :: msize
Called by
Contents
None
Call graph
multi_layer_threesp_target calls p_alloc
restart calls p_alloc
preplasma_multisp calls p_alloc
one_layer_nano_tubes calls p_alloc
one_layer_nano_wires calls p_alloc
multi_layer_gas_target calls p_alloc
multi_layer_twosp_target calls p_alloc
beam_inject calls p_alloc
start calls restart, init
part_distribute calls multi_layer_threesp_target, preplasma_multisp, one_layer_nano_tubes, one_layer_nano_wires, multi_layer_gas_target, multi_layer_twosp_target
env_cycle calls beam_inject
aladyn calls start, env_cycle
init calls part_distribute