part_distribute – ALaDyn
part_distribute Subroutine
38 statements
Source File
public subroutine part_distribute(id, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
part_distribute calls multi_layer_threesp_target, preplasma_multisp, one_layer_nano_tubes, one_layer_nano_wires, multi_layer_gas_target, multi_layer_twosp_target
multi_layer_threesp_target calls xpt, p_alloc, loc_wghx, set_uniform_yz_distrib, wghpt, spec, loc_xpt
preplasma_multisp calls xpt, p_alloc, loc_wghx, set_uniform_yz_distrib, wghpt, spec, loc_xpt
one_layer_nano_tubes calls xpt, mpi_yz_part_distrib, p_alloc, loc_ypt, loc_zpt, loc_wghyz, init_random_seed, ypt, wghpt, spec, gasdev, loc_xpt, zpt
one_layer_nano_wires calls xpt, mpi_yz_part_distrib, p_alloc, loc_ypt, loc_zpt, loc_wghyz, ypt, loc_wghx, wghpt, set_pgrid_ind, spec, loc_xpt, zpt
multi_layer_gas_target calls xpt, p_alloc, loc_wghx, set_uniform_yz_distrib, wghpt, mpi_x_part_distrib, spec, loc_xpt
multi_layer_twosp_target calls xpt, p_alloc, loc_wghx, set_uniform_yz_distrib, wghpt, spec, loc_xpt
mpi_yz_part_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, zpt
set_uniform_yz_distrib calls mpi_yz_part_distrib, loc_ypt, loc_zpt, loc_wghyz, ypt, set_pgrid_ind, zpt
set_pgrid_ind calls ypt, zpt
mpi_x_part_distrib calls xpt, loc_wghx, wghpt, loc_xpt
init calls part_distribute
start calls init
aladyn calls start