particles_inject – ALaDyn
particles_inject Subroutine
60 statements
Source File
public subroutine particles_inject(xmx)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: xmx
Calls
Called by
Contents
None
Call graph
particles_inject calls add_particles, v_realloc, loc_npart
add_particles calls init_random_seed, gasdev
comoving_coordinate calls particles_inject
lp_window_xshift calls particles_inject
env_run calls comoving_coordinate, lp_window_xshift
lp_run calls comoving_coordinate, lp_window_xshift
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle