Part_numbers – ALaDyn
Part_numbers Subroutine
26 statements
Source File
public subroutine Part_numbers()
Arguments
None
Calls
Called by
Contents
None
Call graph
part_numbers calls loc_npart, intvec_distribute
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
aladyn calls part_numbers, env_cycle, lp_cycle
env_cycle calls part_numbers, timing, env_run
lp_window_xshift calls part_numbers
timing calls part_numbers
env_run calls lp_window_xshift
lp_cycle calls timing, lp_run
lp_run calls lp_window_xshift