part_high_gamma_out – ALaDyn
part_high_gamma_out Subroutine
109 statements
Source File
public subroutine part_high_gamma_out(gam_in, timenow)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: gam_in
real(kind=dp), intent(in) :: timenow
Calls
Contents
None
Call graph
part_high_gamma_out calls mpi_write_part, loc_npart, endian, intvec_distribute
mpi_write_part calls mpi_file_close, mpi_file_open, mpi_file_set_view, mpi_file_write
intvec_distribute calls mpi_bcast, mpi_recv, mpi_send