pftw3d – ALaDyn
pftw3d Subroutine
12 statements
Source File
public subroutine pftw3d(w, n1, n2, n2_loc, n3, n3_loc, is)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: w(:,:,:)
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n2_loc
integer, intent(in) :: n3
integer, intent(in) :: n3_loc
integer, intent(in) :: is
Calls
Called by
Contents
None
Call graph
pftw3d calls pftw2d, ftw1d
pftw2d calls ftw1d, swap_xy_3data, swap_xy_3data_inv, swap_xz_3data, swap_xz_3data_inv
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
swap_xy_3data calls yp_next, comm_col, yp_prev
swap_xy_3data_inv calls yp_next, comm_col, yp_prev
swap_xz_3data calls zp_next, zp_prev, comm_col
swap_xz_3data_inv calls zp_next, zp_prev, comm_col
fft_3d_psolv calls pftw3d