pftw2d – ALaDyn
pftw2d Subroutine
51 statements
Source File
public subroutine pftw2d(w, n1, n2, n2_loc, n3, n3_loc, is)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: w(:,:,:)
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n2_loc
integer, intent(in) :: n3
integer, intent(in) :: n3_loc
integer, intent(in) :: is
Calls
Called by
Contents
None
Call graph
pftw2d calls swap_xy_3data, ftw1d, swap_xy_3data_inv, swap_xz_3data, swap_xz_3data_inv
swap_xy_3data calls yp_next, comm_col, yp_prev
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
swap_xy_3data_inv calls yp_next, comm_col, yp_prev
swap_xz_3data calls zp_next, zp_prev, comm_col
swap_xz_3data_inv calls zp_next, zp_prev, comm_col
pftw3d calls pftw2d
fft_2d_psolv calls pftw2d
set_wake_potential calls fft_2d_psolv
fft_3d_psolv calls pftw3d