pp_lapl – ALaDyn
pp_lapl Subroutine
83 statements
Source File
public subroutine pp_lapl(av, source, ic1, ic2)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: av(:,:,:,:)
real(kind=dp), intent(inout) :: source(:,:,:,:)
integer, intent(in) :: ic1
integer, intent(in) :: ic2
Calls
Called by
Contents
None
Call graph
pp_lapl calls loc_yg, loc_zg
env_lpf_solve calls pp_lapl
advance_lpf_envelope calls env_lpf_solve
env_lpf2_evolve calls advance_lpf_envelope
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle