pspecies_distribute – ALaDyn
pspecies_distribute Subroutine
50 statements
Source File
private subroutine pspecies_distribute(loc_sp, t_x, ch, q, ic, i2, p)
Arguments
Type Intent Optional Attributes Name
type(species), intent(inout) :: loc_sp
real(kind=dp), intent(in) :: t_x
real(kind=dp), intent(in) :: ch
integer, intent(in) :: q
integer, intent(in) :: ic
integer, intent(in) :: i2
integer, intent(out) :: p
Calls
Contents
None
Call graph
pspecies_distribute calls loc_zpt, loc_ypt, loc_wghyz, init_random_seed, loc_wghx, gasdev, loc_xpt