read_main_input – ALaDyn
read_main_input Subroutine
12 statements
Source File
public subroutine read_main_input()
Arguments
None
Calls
Called by
Contents
None
Call graph
read_main_input calls read_input_nml
read_input_nml calls consistency_check_number_of_particles_comp, consistency_check_grid
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
from_ppc_to_npx_npy_npz calls isprime
start calls read_main_input
aladyn calls start