restart – ALaDyn
restart Subroutine
369 statements
Source File
public subroutine restart(it_loc, tloc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: it_loc
real(kind=dp), intent(out) :: tloc
Calls
Called by
Contents
None
Call graph
restart calls vint_2d_bcast, wghpt, vint_bcast, exchange_2d_grdata, loc_npart, up, up0, intvec_distribute, ebf, env, env1, p_alloc, loc_wghyz, exchange_1d_grdata, xpt, loc_ypt, loc_zpt, fluid_x_profile, real_bcast, spec, fluid_yz_profile
vint_bcast calls mpi_bcast
intvec_distribute calls mpi_bcast, mpi_recv, mpi_send
real_bcast calls mpi_bcast
start calls restart
aladyn calls start