set_wake_potential – ALaDyn
set_wake_potential Subroutine
21 statements
Source File
public subroutine set_wake_potential()
Arguments
None
Calls
Contents
None
Call graph
set_wake_potential calls fill_curr_yzxbdsdata, fft_2d_psolv, fill_density_data, loc_npart, spec, jc
fill_curr_yzxbdsdata calls exchange_bdx_data
fft_2d_psolv calls mpi_ftw_alloc, all_gather_dpreal, beam_2d_potential, mpi_yzft_ord, pftw2d, pftw2d_sc, ftw_init, mpi_ftw_dalloc, unif_to_str_field_interp, ftw_end, ft_overset_grid
fill_density_data calls loc_zgrid, y, x, loc_ygrid, z
pftw2d calls swap_xy_3data, ftw1d, swap_xy_3data_inv, swap_xz_3data, swap_xz_3data_inv
pftw2d_sc calls swap_xy_3data, swap_xy_3data_inv, ftw1d_sc, swap_xz_3data, swap_xz_3data_inv
unif_to_str_field_interp calls yft_ind, loc_yg, loc_zft, zft_ind, loc_zg, loc_yft
ft_overset_grid calls zp_next, zp_prev, yp_next, comm_col, yp_prev
swap_xy_3data calls yp_next, comm_col, yp_prev
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
swap_xy_3data_inv calls yp_next, comm_col, yp_prev
ftw1d_sc calls fftw_execute_r2r, determine_kind, logical_dimension
swap_xz_3data calls zp_next, zp_prev, comm_col
swap_xz_3data_inv calls zp_next, zp_prev, comm_col