set_poloidal_ex_fields – ALaDyn
set_poloidal_ex_fields Subroutine
19 statements
Source File
public subroutine set_poloidal_ex_fields(ef1, i1, i2, j1, j2, k1, k2, bpoloidal, rpoloidal)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef1(:,:,:,:)
integer, intent(in) :: i1
integer, intent(in) :: i2
integer, intent(in) :: j1
integer, intent(in) :: j2
integer, intent(in) :: k1
integer, intent(in) :: k2
real(kind=dp), intent(in) :: bpoloidal
real(kind=dp), intent(in) :: rpoloidal
Calls
Contents
None
Call graph
set_poloidal_ex_fields calls loc_yg, loc_zg, loc_xg