set_lpf_acc – ALaDyn
set_lpf_acc Subroutine
14 statements
Source File
public subroutine set_lpf_acc(ef, sp_loc, apt, np, nf)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: ef(:,:,:,:)
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: apt(:,:)
integer, intent(in) :: np
integer, intent(in) :: nf
Calls
Contents
None
Call graph
set_lpf_acc calls set_part3d_hcell_acc, set_part2d_hcell_acc, set_part1d_acc
set_part3d_hcell_acc calls qlh_3d_spline, set_local_3d_positions
set_part2d_hcell_acc calls qlh_2d_spline, set_local_2d_positions
set_part1d_acc calls qqh_1d_spline
set_local_3d_positions calls map3d_part_sind
set_local_2d_positions calls map2dy_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid