set_local_2d_positions – ALaDyn
set_local_2d_positions Subroutine
27 statements
Source File
public subroutine set_local_2d_positions(pt_loc, n1, np)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: pt_loc(:,:)
integer, intent(in) :: n1
integer, intent(in) :: np
Calls
Called by
Contents
None
Call graph
set_local_2d_positions calls map2dy_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
set_grid_charge_and_jx calls set_local_2d_positions
set_grid_env_den_energy calls set_local_2d_positions
set_part2d_hcell_acc calls set_local_2d_positions
ncdef_2d_curr calls set_local_2d_positions
set_env_grad_interp calls set_local_2d_positions
esirkepov_2d_curr calls set_local_2d_positions
set_env_density calls set_local_2d_positions
set_ion_efield calls set_local_2d_positions
set_env_acc calls set_local_2d_positions
set_grid_charge calls set_local_2d_positions
set_grid_den_energy calls set_local_2d_positions
set_ion_env_field calls set_local_2d_positions
set_lpf_acc calls set_part2d_hcell_acc
curr_accumulate calls ncdef_2d_curr, esirkepov_2d_curr