set_uniform_yz_distrib – ALaDyn
set_uniform_yz_distrib Subroutine
131 statements
Source File
private subroutine set_uniform_yz_distrib(nyh_in, nc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
integer, intent(in) :: nc
Calls
Called by
Contents
None
Call graph
set_uniform_yz_distrib calls mpi_yz_part_distrib, loc_zpt, loc_ypt, loc_wghyz, set_pgrid_ind, ypt, zpt
mpi_yz_part_distrib calls loc_zpt, loc_ypt, loc_wghyz, ypt, zpt
set_pgrid_ind calls ypt, zpt
preplasma_multisp calls set_uniform_yz_distrib
multi_layer_twosp_target calls set_uniform_yz_distrib
multi_layer_gas_target calls set_uniform_yz_distrib
multi_layer_threesp_target calls set_uniform_yz_distrib
part_distribute calls preplasma_multisp, multi_layer_twosp_target, multi_layer_gas_target, multi_layer_threesp_target
init calls part_distribute
start calls init
aladyn calls start