set_pgrid_ind – ALaDyn
set_pgrid_ind Subroutine
68 statements
Source File
private subroutine set_pgrid_ind(npy, npz, ic)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npy
integer, intent(in) :: npz
integer, intent(in) :: ic
Calls
Called by
Contents
None
Call graph
set_pgrid_ind calls ypt, zpt
one_layer_nano_wires calls set_pgrid_ind
set_uniform_yz_distrib calls set_pgrid_ind
multi_layer_threesp_target calls set_uniform_yz_distrib
multi_layer_twosp_target calls set_uniform_yz_distrib
multi_layer_gas_target calls set_uniform_yz_distrib
preplasma_multisp calls set_uniform_yz_distrib
part_distribute calls one_layer_nano_wires, multi_layer_threesp_target, multi_layer_twosp_target, multi_layer_gas_target, preplasma_multisp
init calls part_distribute
start calls init
aladyn calls start