set_part2d_hcell_acc – ALaDyn
set_part2d_hcell_acc Subroutine
85 statements
Source File
public subroutine set_part2d_hcell_acc(ef, sp_loc, pt, np, ndf)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: ef(:,:,:,:)
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pt(:,:)
integer, intent(in) :: np
integer, intent(in) :: ndf
Calls
Called by
Contents
None
Call graph
set_part2d_hcell_acc calls qlh_2d_spline, set_local_2d_positions
set_local_2d_positions calls map2dy_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
set_lpf_acc calls set_part2d_hcell_acc