set_env_density – ALaDyn
set_env_density Subroutine
54 statements
Source File
public subroutine set_env_density(efp, av, np, ic)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: efp(:,:)
real(kind=dp), intent(inout) :: av(:,:,:,:)
integer, intent(in) :: np
integer, intent(in) :: ic
Calls
Contents
None
Call graph
set_env_density calls set_local_2d_positions, qden_3d_wgh, qden_2d_wgh, set_local_3d_positions
set_local_2d_positions calls map2dy_part_sind
set_local_3d_positions calls map3d_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid