Start – ALaDyn
Start Subroutine
193 statements
Source File
public subroutine Start()
Start subroutine. It reads the input file, initializes the variables and allocates the needed arrays before to start the simulation.
Arguments
None
Calls
Called by
Contents
None
Call graph
start calls ion_min, set_ftgrid, set_fxgrid, set_loc_grid_param, create_initial_folders, end_parallel, yft_ind, read_main_input, mpi_barrier, init, v_alloc, set_field_param, restart, loc_yg, set_fyzxgrid, atomic_number, loc_yft, fluid_alloc, set_output_grid, mpi_loc_grid, set_initial_param, float, write_read_nml, loc_yftgrid, loc_ygrid, mpi_buffer_alloc, start_parallel
set_ftgrid calls select_str_to_ft_grid, set_ftyzgrid
read_main_input calls read_input_nml
init calls lp_pulse, set_envelope, cp_pulse, part_distribute
restart calls vint_2d_bcast, wghpt, vint_bcast, exchange_2d_grdata, loc_npart, up, up0, intvec_distribute, ebf, env, env1, p_alloc, loc_wghyz, exchange_1d_grdata, xpt, loc_ypt, loc_zpt, fluid_x_profile, real_bcast, spec, fluid_yz_profile
set_initial_param calls z, set_grid, y
lp_pulse calls y0_cent, lp_end, loc_xgrid, init_lp_inc0_fields, z0_cent, xc_loc, lp_in, xf_loc, lp_delay, lpx
vint_bcast calls mpi_bcast
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
set_envelope calls y0_cent, lp_end, loc_xgrid, init_gprof_envelope_field, z0_cent, init_envelope_field, xc_loc, lp_in, xf_loc, lp_delay, lpx
cp_pulse calls init_cp_fields, lp_end, loc_xgrid, lp_in, lpx
read_input_nml calls consistency_check_grid, consistency_check_number_of_particles_comp
part_distribute calls multi_layer_threesp_target, multi_layer_gas_target, preplasma_multisp, one_layer_nano_tubes, one_layer_nano_wires, multi_layer_twosp_target
real_bcast calls mpi_bcast
init_cp_fields calls loc_yg, loc_ygrid, get_plane_wave_cp, loc_zg, get_laser_fields_cp, loc_zgrid, loc_xg
init_gprof_envelope_field calls loc_yg, loc_ygrid, loc_zg, loc_zgrid, loc_xg
multi_layer_threesp_target calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib
init_lp_inc0_fields calls loc_yg, loc_ygrid, get_2dlaser_gprof_fields_lp, get_laser_gprof_fields_lp, loc_zg, loc_zgrid, get_laser_fields_lp, get_2dlaser_fields_lp, loc_xg, get_plane_wave_lp
multi_layer_gas_target calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib, mpi_x_part_distrib
preplasma_multisp calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib
init_envelope_field calls loc_yg, loc_ygrid, loc_zg, loc_zgrid, loc_xg
one_layer_nano_tubes calls wghpt, p_alloc, loc_wghyz, xpt, loc_ypt, loc_zpt, spec, loc_xpt, zpt, mpi_yz_part_distrib, init_random_seed, ypt, gasdev
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
one_layer_nano_wires calls wghpt, p_alloc, loc_wghyz, xpt, loc_ypt, loc_zpt, spec, loc_xpt, loc_wghx, set_pgrid_ind, zpt, mpi_yz_part_distrib, ypt
multi_layer_twosp_target calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib
from_ppc_to_npx_npy_npz calls isprime
set_pgrid_ind calls zpt, ypt
mpi_yz_part_distrib calls loc_wghyz, loc_ypt, loc_zpt, zpt, ypt
set_uniform_yz_distrib calls loc_wghyz, loc_ypt, loc_zpt, set_pgrid_ind, zpt, mpi_yz_part_distrib, ypt
mpi_x_part_distrib calls wghpt, xpt, loc_xpt, loc_wghx
aladyn calls start