start_parallel – ALaDyn
start_parallel Subroutine
117 statements
Source File
public subroutine start_parallel(ncmp, p_ind, b_ind)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncmp
integer, intent(in) :: p_ind
integer, intent(in) :: b_ind
Calls
Contents
None
Call graph
start_parallel calls mpi_comm_size, mpi_type_contiguous, init_random_seed, mpi_comm_rank, mpi_init, mpi_type_commit, check_decomposition