swap_xy_3data – ALaDyn
swap_xy_3data Subroutine
51 statements
Source File
public subroutine swap_xy_3data(wp1, wp2, n1_loc, n2_loc, n3_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: wp1(:,:,:)
real(kind=dp), intent(out) :: wp2(:,:,:)
integer, intent(in) :: n1_loc
integer, intent(in) :: n2_loc
integer, intent(in) :: n3_loc
Calls
Called by
Contents
None
Call graph
swap_xy_3data calls comm_col, yp_prev, yp_next
pftw2d calls swap_xy_3data
pftw2d_sc calls swap_xy_3data
pftw3d calls pftw2d
fft_2d_psolv calls pftw2d, pftw2d_sc
pftw3d_sc calls pftw2d_sc
set_wake_potential calls fft_2d_psolv
fft_3d_psolv calls pftw3d, pftw3d_sc