t_particles_collect – ALaDyn
t_particles_collect Subroutine
67 statements
Source File
public subroutine t_particles_collect(time_ind)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: time_ind
Calls
Contents
None
Call graph
t_particles_collect calls loc_tpart, intvec_distribute, exchange_1d_grdata, loc_zgrid, loc_npart, loc_ygrid, loc_xgrid, pdata_tracking, spec, track_aux, str_indx