timing – ALaDyn
timing Subroutine
29 statements
Source File
public subroutine timing()
Arguments
None
Calls
Called by
Contents
None
Call graph
timing calls part_numbers, tot_num_part, max_pmemory_check
part_numbers calls loc_npart, intvec_distribute
tot_num_part calls loc_npart
max_pmemory_check calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
lp_cycle calls timing
env_cycle calls timing
aladyn calls lp_cycle, env_cycle