v_realloc – ALaDyn
v_realloc Subroutine
14 statements
Source File
public subroutine v_realloc(vdata, npt_new, ndv)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), allocatable :: vdata(:,:)
integer, intent(in) :: npt_new
integer, intent(in) :: ndv
Called by
Contents
None
Call graph
ionization_cycle calls v_realloc
reset_all_part_dist calls v_realloc
cell_part_dist calls v_realloc
comoving_coordinate calls cell_part_dist
lp_window_xshift calls cell_part_dist
env_run calls comoving_coordinate, lp_window_xshift
lp_run calls comoving_coordinate, lp_window_xshift
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle