wave_field_left_inject – ALaDyn
wave_field_left_inject Subroutine
32 statements
Source File
public subroutine wave_field_left_inject(ef, x_left)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: ef(:,:,:,:)
real(kind=dp), intent(in) :: x_left
Calls
Contents
None
Call graph
wave_field_left_inject calls lp_in, inflow_lp_fields, lp_end, xf_loc
inflow_lp_fields calls get_plane_wave_lp, get_laser_fields_lp, get_2dlaser_fields_lp, loc_yg, loc_xg, get_2dlaser_gprof_fields_lp, loc_zg