fftw_execute_dft_r2c – ALaDyn
fftw_execute_dft_r2c Interface
512 statements
Source File
interface
Called by
public subroutine fftw_execute_dft_r2c(p, in, out) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
type(C_PTR), value :: p
real(kind=C_DOUBLE), intent(inout), dimension(*) :: in
complex(kind=C_DOUBLE_COMPLEX), intent(out), dimension(*) :: out
Call graph
ftw1d calls fftw_execute_dft_r2c
ftw1d_st calls fftw_execute_dft_r2c
pftw2d calls ftw1d
pftw3d calls ftw1d, pftw2d
fft_2d_psolv calls pftw2d
fft_3d_psolv calls pftw3d
set_wake_potential calls fft_2d_psolv