aladyn – ALaDyn
aladyn Program
168 statements
Source File
Uses
start_all
diag_part_and_fields
run_data_info
pic_out_util
pic_out
init_beam_part_distrib
pic_evolve
env_evolve
Calls
Contents
Subroutines
Lp_cycle Env_cycle data_out
Subroutines
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
subroutine Env_cycle()
Arguments
None
subroutine data_out()
Arguments
None
Call graph
aladyn calls end_parallel, part_numbers, env_cycle, initial_run_info, start, lp_cycle, mpi_barrier, max_pmemory_check, final_run_info
part_numbers calls loc_npart, intvec_distribute
env_cycle calls part_numbers, error_message, env_run, beam_inject, timing, data_out
start calls end_parallel, mpi_barrier, ion_min, set_ftgrid, set_fxgrid, set_loc_grid_param, create_initial_folders, yft_ind, read_main_input, init, v_alloc, set_field_param, restart, loc_yg, set_fyzxgrid, atomic_number, loc_yft, fluid_alloc, set_output_grid, mpi_loc_grid, set_initial_param, float, write_read_nml, loc_yftgrid, loc_ygrid, mpi_buffer_alloc, start_parallel
lp_cycle calls error_message, lp_run, timing, data_out
max_pmemory_check calls allreduce_dpreal
set_ftgrid calls select_str_to_ft_grid, set_ftyzgrid
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
read_main_input calls read_input_nml
lp_run calls lpf2_evolve, comoving_coordinate, lp_window_xshift
init calls lp_pulse, set_envelope, cp_pulse, part_distribute
restart calls loc_npart, intvec_distribute, vint_2d_bcast, wghpt, vint_bcast, exchange_2d_grdata, up, up0, ebf, env, env1, p_alloc, loc_wghyz, exchange_1d_grdata, xpt, loc_ypt, loc_zpt, fluid_x_profile, real_bcast, spec, fluid_yz_profile
env_run calls comoving_coordinate, lp_window_xshift, env_lpf2_evolve
beam_inject calls loc_npart, loc_nbpart, pot, fill_ebfield_yzxbdsdata, beam_data, mpi_beam_ftgrid_distribute, lp_end, ebf, mpi_beam_distribute, ebfp, ebf_bunch, initial_beam_fields, p_alloc, init_random_seed, jc, ebfb, spec, bunch
timing calls part_numbers, max_pmemory_check, tot_num_part
set_initial_param calls z, set_grid, y
allreduce_dpreal calls mpi_allreduce
data_out calls part_pdata_out, env_two_fields_out, envar, create_timestep_folder, env_fields_out, fields_out, fields_out_new, fluid_den_mom_out, den_energy_out, prl_den_energy_interp
part_pdata_out calls loc_npart, intvec_distribute, mpi_write_part, endian
lpf2_evolve calls ion_min, loc_npart, atomic_number, ebfp, jc, spec, pfields_prepare, update_adam_bash_fluid_variables, advance_lpf_fields, set_momentum_density_flux, init_random_seed, fluid_curr_accumulate
lp_pulse calls lp_end, y0_cent, loc_xgrid, init_lp_inc0_fields, z0_cent, xc_loc, lp_in, xf_loc, lp_delay, lpx
fill_ebfield_yzxbdsdata calls exchange_bdx_data
beam_data calls ebfb, exchange_2d_grdata, unit_charge
env_two_fields_out calls exchange_pdata
vint_bcast calls mpi_bcast
mpi_beam_ftgrid_distribute calls loc_nbpart, ebfb, bunch
comoving_coordinate calls cell_part_dist, particles_inject
lp_window_xshift calls part_numbers, fluid_left_xshift, fields_left_xshift, cell_part_dist, particles_inject
mpi_beam_distribute calls loc_nbpart, ebfb, bunch
envar calls loc_npart, allreduce_dpreal, enb_bunch, mass, envelope_struct_data
env_fields_out calls exchange_pdata
initial_beam_fields calls loc_yg, loc_zg
set_envelope calls lp_end, y0_cent, loc_xgrid, init_gprof_envelope_field, z0_cent, init_envelope_field, xc_loc, lp_in, xf_loc, lp_delay, lpx
fields_out calls exchange_pdata, endian
cp_pulse calls lp_end, init_cp_fields, loc_xgrid, lp_in, lpx
read_input_nml calls consistency_check_grid, consistency_check_number_of_particles_comp
env_lpf2_evolve calls ion_min, loc_npart, atomic_number, ebfp, init_random_seed, jc, spec, advance_lpf_envelope, env_fields_average, update_adam_bash_fluid_variables, env_two_fields_average, enable_ionization, flux, advance_lpf_fields, set_env_momentum_density_flux, env_den_collect, env_amp_two_fields_prepare, curr_mpi_collect, env_amp_prepare, set_env_density, fluid_curr_accumulate
fields_out_new calls mpi_write_field, endian
tot_num_part calls loc_npart
part_distribute calls multi_layer_threesp_target, multi_layer_gas_target, preplasma_multisp, one_layer_nano_tubes, one_layer_nano_wires, multi_layer_twosp_target
fluid_den_mom_out calls exchange_pdata, endian
den_energy_out calls exchange_pdata, endian
prl_den_energy_interp calls loc_npart, loc_yg, env, jc, spec, den_zyxbd, loc_zg, mass
real_bcast calls mpi_bcast
init_cp_fields calls loc_yg, loc_ygrid, loc_zg, get_plane_wave_cp, get_laser_fields_cp, loc_zgrid, loc_xg
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
init_gprof_envelope_field calls loc_yg, loc_ygrid, loc_zg, loc_zgrid, loc_xg
env_fields_average calls env_grad
mpi_write_part calls mpi_file_set_view, mpi_file_write, mpi_file_close, mpi_file_open
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
multi_layer_threesp_target calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib
init_lp_inc0_fields calls loc_yg, loc_ygrid, loc_zg, get_2dlaser_gprof_fields_lp, get_laser_gprof_fields_lp, loc_zgrid, get_laser_fields_lp, get_2dlaser_fields_lp, loc_xg, get_plane_wave_lp
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, nc_fluid_density_momenta, field_xyzbd
multi_layer_gas_target calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib, mpi_x_part_distrib
preplasma_multisp calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib
advance_lpf_fields calls fill_ebfield_yzxbdsdata, field_xadvect, rotb, rote, ef_bds, bf_bds
env_den_collect calls loc_yg, loc_zg, fill_curr_yzxbdsdata, den_zyxbd
init_envelope_field calls loc_yg, loc_ygrid, loc_zg, loc_zgrid, loc_xg
env_amp_two_fields_prepare calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, jc_xyzbd, djc
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
one_layer_nano_tubes calls wghpt, p_alloc, loc_wghyz, init_random_seed, xpt, loc_ypt, loc_zpt, spec, loc_xpt, zpt, mpi_yz_part_distrib, ypt, gasdev
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
one_layer_nano_wires calls wghpt, p_alloc, loc_wghyz, xpt, loc_ypt, loc_zpt, spec, loc_xpt, loc_wghx, set_pgrid_ind, zpt, mpi_yz_part_distrib, ypt
multi_layer_twosp_target calls wghpt, p_alloc, xpt, spec, loc_xpt, loc_wghx, set_uniform_yz_distrib
env_amp_prepare calls env_grad
mpi_write_field calls mpi_file_set_view, mpi_file_write, mpi_file_close, mpi_file_open
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
envelope_struct_data calls allreduce_dpreal
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
particles_inject calls loc_npart, v_realloc, add_particles
bunch_corr calls allreduce_dpreal
fill_curr_yzxbdsdata calls exchange_bdx_data
field_xadvect calls trid_der1
rotb calls loc_yg, loc_zg
env_maxw_solve calls potential_lapl
from_ppc_to_npx_npy_npz calls isprime
rote calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
set_pgrid_ind calls zpt, ypt
nc_fluid_density_momenta calls loc_yg, loc_zg
mpi_yz_part_distrib calls loc_wghyz, loc_ypt, loc_zpt, zpt, ypt
env_bds calls loc_yg, loc_zg
set_uniform_yz_distrib calls loc_wghyz, loc_ypt, loc_zpt, set_pgrid_ind, zpt, mpi_yz_part_distrib, ypt
mpi_x_part_distrib calls wghpt, xpt, loc_xpt, loc_wghx
env_lpf_solve calls pp_lapl
add_particles calls init_random_seed, gasdev
bf_bds calls loc_yg, loc_zg, loc_xg
pp_lapl calls loc_yg, loc_zg